### ISSUE TITLE
side-by-side with original analysis

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/LDATS#78]
create a document that shows the differences between the package and the analysis done for the paper

**Comment by diazrenata** [comment]
rmd to-do as of 1/13/19:

* confirm that not adjusting rodent data does not impact LDA results (if it does, it should be due to rounding-type artifacts - changing proportions because you can only add or subtract whole rats)
* explain why ^^ is true
* combine paper/ldats changepoint scripts into one .Rmd
* stash model objects somewhere linkable in the cloud
* illustrate moving 'date' through ldats as an unused covariate column 
* illustrate interpolating dates for changepoint estimates between observation dates

**Comment by juniperlsimonis** [comment]
@diazrenata slayed it in PR #105
